### ISSUE TITLE
An error keeps occuring when trying to run software using the test image.

### ISSUE THREAD

**Issue by Neopolaria** [UWCubeSat/lost#129]
![image](https://github.com/UWCubeSat/lost/assets/122650816/33416548-13be-47b1-a08e-6614f233eadb)

We are using a raspberry pi, will be used aboard a sounding rocket

**Comment by markasoftware** [comment]
Admittedly it's a poor error message, but you can tell by the "reading -1 bytes of database" that something's wrong with the database. Did you generate `my-database.dat` according to the instructions?

**Comment by Neopolaria** [comment]
Hi there! Yes, I copied the database creation command from the git. Should I delete the database and try again?

**Comment by markasoftware** [comment]
Can you confirm that the database file `my-database.dat` actually exists?

**Comment by Neopolaria** [comment]
Weird, it doesn't seem to exist, I remember making it. I'll try making it again

**Comment by Neopolaria** [comment]
After remaking the database, I used whereis and it still doesn't seem to exist![image](https://github.com/UWCubeSat/lost/assets/122650816/0d79e7ae-e62d-4906-94a8-15a8903cf5ee)

**Comment by Neopolaria** [comment]
Never mind, it worked! Thank you very much!

**Comment by markasoftware** [comment]
I just pushed a new commit that should give a better error message. Also, the right way to check if the file exists is using `ls`! The purpose of `whereis` is to find where an executable is, for example you can run `whereis gcc` and it will tell you the path to the `gcc` program (or, more fun, `whereis whereis` tells you where the `whereis` program itself is located!)

**Comment by markasoftware** [comment]
(`stat` is another great command for checking if a file exists and viewing info about it)
