### ISSUE TITLE
Question about formulas for camera

### ISSUE THREAD

**Issue by JyKlub** [UWCubeSat/lost#131]
![image](https://github.com/user-attachments/assets/03bb6496-1d2e-461d-b416-d3c181fb406a)
Hi, i don't think the two functions marked here match, i believe in the FovToFocalLength function the pixelSize variable is missing, should have appeared in the numerator, goes like: 
FocalLength = xResolution * pixelSize / DECIMAL(2.0) / DECIMAL_TAN(xFov/2)
or perhaps you are using a default pixelSize of 1?

**Comment by markasoftware** [comment]
Hello, yes the FovToFocalLength returns the focal length measured in pixels, which is equivalent to pixelSize = 1. It is not documented well. Focal length measured in pixels is what we mainly use internally. See FocalLengthFromOptions in io.cpp for some context.

**Comment by JyKlub** [comment]
> Hello, yes the FovToFocalLength returns the focal length measured in pixels, which is equivalent to pixelSize = 1. It is not documented well. Focal length measured in pixels is what we mainly use internally. See FocalLengthFromOptions in io.cpp for some context.

Thanks!
