### ISSUE TITLE
man pages out of date

### ISSUE THREAD

**Issue by karenhaining** [UWCubeSat/lost#54]
For example, the man page for pipeline says there is a --compare-stars flag, but that gives an error because in pipeline-options.hpp the command is actually --compare-star-ids.

There may be more errors (also check synopsis and description!).

**Comment by karenhaining** [comment]
Also:
For pipeline's pixel-size option, there's compile error `troff: documentation/pipeline.man:38: warning: can't find special character '*m'`. Basically it doesn't recognize \[*m] as mu. (If no solution, maybe just write micro-m or sth). 

And there's a random question mark at the end of the printout when you run ./lost pipeline --help

**Comment by markasoftware** [comment]
I think these are mostly up to date now.
