### ISSUE TITLE
Fix broken build-test-lint workflow

### ISSUE THREAD

**Issue by kjy5** [UWCubeSat/lost#57]
Changes to workflow causes it to not work anymore
- Just need to separate out linting job from build job. Cannot run python inside the container

**Comment by markasoftware** [comment]
my bad, i tried to put them together.

Do you know why python doesn't work in the container?

**Comment by kjy5** [comment]
Mostly likely because the python action (which is built by GitHub) is designed to run on the ubuntu environment provided by GitHub. Separate jobs are actually better because they can run concurrently. That's why I had a build job and a lint job because they don't depend on each other meaning they can run concurrently

**Comment by markasoftware** [comment]
Okay then, feel free to revert it back to how it was before.
