### ISSUE TITLE
Tetra integrate database generation into lost

### ISSUE THREAD

**Issue by zeddie888** [UWCubeSat/lost#58]
Integrate Kenneth's database generation code into LOST for use in TetraStarIdAlgorithm::Go().
Also figure out the following quirks:
1. Why are some stars in tetra3's star table not found in BSC5
2. Exactly 3 missing stars in our generated star table

Suggest first understanding how database generation works, format of "database" files, etc.

**Comment by zeddie888** [comment]
Database generation is now "fixed". There are some suspicious elements, but testing with star-id.cpp correctly identifies stars for now
Specifically:
1. Star table appears fine, matches expected quite closely
2. Pattern catalog is missing around 1000 patterns out of 9 million

**Comment by zeddie888** [comment]
Possible issue with hashing (database generation step): the original paper states that in most cases, one disk access is enough to g grab a Pattern from the hash table given some index.

However, while doing quadratic probing to insert a Pattern into the catalog, the number of collisions becomes around 30-40, which is extremely suspicious

**Comment by markasoftware** [comment]
I think this is done
