### ISSUE TITLE
the code gives a runtime error upon compilation

### ISSUE THREAD

**Issue by firefreeze234** [UWCubeSat/lost#6]

**Comment by markasoftware** [comment]
Could you elaborate on your issue?

The readme is not totally up-to-date -- you will also need to install `libeigen3-dev` on a modern Debian based system, or download Eigen3 manually and put it in the `vendor` folder.

Either way, LOST doesn't work all that well right now, though I welcome you to play around with the features it does have. If you  want to get involved in development, shoot me an email: mark at markasoftware dot com

**Comment by firefreeze234** [comment]
> The readme is not totally up-to-date -- you will also need to install `libeigen3-dev` on a modern Debian based system, or download Eigen3 manually and put it in the `vendor` folder.
> Thanks a lot! will try running that 
> Either way, LOST doesn't work all that well right now, though I welcome you to play around with the features it does have. If you want to get involved in development, shoot me an email: mark at markasoftware dot com
> I would have loved to! But I'm currently focused on a cubesat project of our own in my university. Can you elaborate as to why exactly does LOST doesn't work well?

**Comment by markasoftware** [comment]
Currently, lost can generate simulated star images and identify them correctly using three different algorithms. Real photos taken with a camera look almost identical to the generated ones, but are not correctly identified. We are currently working to figure out why this is, and make our algorithms more robust. Probably within a month LOST's essential functionality will be ready. If you want to use LOST in your cubesat I highly recommend scheduling a call with our star tracking team so we can collaborate.

**Comment by firefreeze234** [comment]
Sure!
it would be great! We can have a zoom call or something maybe

**Comment by firefreeze234** [comment]
hey, I'll probably close the issue now. Me and the team will love to talk about implementation of LOST in our cubesat mission. Please feel free to approach me at kaustubh.murudkar@gmail.com

**Comment by markasoftware** [comment]
Sounds good, I'll be in touch soon!
