### ISSUE TITLE
Serialization of database, duplicate work

### ISSUE THREAD

**Issue by zeddie888** [UWCubeSat/lost#63]
Database serialization requires some duplicate work, especially if you don't know the required size upfront

For example, Tetra's database does the following
1. Generate the entire pattern catalog, do nothing with it, but record its length
2. Make the buffer large enough to hold new database
3. Generate the entire pattern catalog AGAIN, this time writing bytes into buffer

**Comment by markasoftware** [comment]
One solution is to, instead of having a `Serialize...Length` function and a `Serialize...` function separately, have the `Serialize...` function return an `std::vector`, which contains both length and actual data.
