### ISSUE TITLE
Change method of reporting "unknown attitude"

### ISSUE THREAD

**Issue by zeddie888** [UWCubeSat/lost#77]
Currently there is no distinction in PipelineOutput between "not enough stars identified to calculate attitude" and "all identified stars were wrong, producing bogus output". 

Quoting Mark:
> Probably best to modify Pipeline::Go so that if there aren't enough StarIdentifiers, it doesn't try to run the attitude estimation algorithm, and therefore no attitude will be stored in the PipelineOutput, and this can be detected in the PipelineComparatorAttitude to report what fraction of the attitudes were correct, incorrect, and unknown

**Comment by markasoftware** [comment]
Fixed on master
